# This file is generated by build_types.py on 2025-08-21.
# do NOT modifiy

from ._stationeers import Color as _Color
from ._stationeers import DeviceTyped as _DeviceTyped
from ._stationeers import FieldDesc as _FieldDesc
from ._stationeers import FieldDescW as _FieldDescW
from ._stationeers import mk_field as _mk_field
from ._stationeers import mk_field_ro as _mk_field_ro


class _BaseGas:
    RatioCarbonDioxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidCarbonDioxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrogen: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrousOxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidOxygen: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidPollutant: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidVolatiles: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogen: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygen: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutant: _FieldDesc[float] = _mk_field_ro(float)
    RatioSteam: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatiles: _FieldDesc[float] = _mk_field_ro(float)
    RatioWater: _FieldDesc[float] = _mk_field_ro(float)


class _BaseGasInput:
    RatioCarbonDioxideInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidCarbonDioxideInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrogenInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrousOxideInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidOxygenInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidPollutantInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidVolatilesInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogenInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxideInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygenInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutantInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioSteamInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatilesInput: _FieldDesc[float] = _mk_field_ro(float)
    RatioWaterInput: _FieldDesc[float] = _mk_field_ro(float)


class _BaseGasOutput:
    RatioCarbonDioxideOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidCarbonDioxideOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrogenOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrousOxideOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidOxygenOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidPollutantOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidVolatilesOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogenOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxideOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygenOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutantOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioSteamOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatilesOutput: _FieldDesc[float] = _mk_field_ro(float)
    RatioWaterOutput: _FieldDesc[float] = _mk_field_ro(float)


class _BaseGasOutput2:
    RatioCarbonDioxideOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidCarbonDioxideOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrogenOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidNitrousOxideOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidOxygenOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidPollutantOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioLiquidVolatilesOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogenOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxideOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygenOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutantOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioSteamOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatilesOutput2: _FieldDesc[float] = _mk_field_ro(float)
    RatioWaterOutput2: _FieldDesc[float] = _mk_field_ro(float)


class _Power:
    On: _FieldDescW[bool] = _mk_field(bool)
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    RequiredPower: _FieldDesc[int] = _mk_field_ro(int)


class _On:
    On: _FieldDescW[bool] = _mk_field(bool)


class _Activate:
    Activate: _FieldDescW = _mk_field()


class _Lock:
    Lock: _FieldDescW[bool] = _mk_field(bool)


class _Open:
    Open: _FieldDescW[bool] = _mk_field(bool)


class _Error:
    Error: _FieldDesc[bool] = _mk_field_ro(bool)


class _Ratio:
    Ratio: _FieldDesc = _mk_field_ro()


class _Maximum:
    Maximum: _FieldDesc = _mk_field_ro()


class _SettingW:
    Setting: _FieldDescW = _mk_field()


class _SettingR:
    Setting: _FieldDesc = _mk_field_ro()


class _Mode:
    Mode: _FieldDescW = _mk_field()


class _ModeR:
    Mode: _FieldDesc = _mk_field_ro()


class _Temperature:
    Pressure: _FieldDesc = _mk_field_ro()
    Temperature: _FieldDesc = _mk_field_ro()


class _PollWater:
    RatioPollutedWater: _FieldDesc = _mk_field_ro()


class _Combustion:
    Combustion: _FieldDesc = _mk_field_ro()
    TotalMoles: _FieldDesc = _mk_field_ro()


class _Idle:
    Idle: _FieldDesc = _mk_field_ro()


class _ClearMemory:
    ClearMemory: _FieldDescW = _mk_field()


class _Hydrogen:
    RatioHydrogen: _FieldDesc = _mk_field_ro()
    RatioLiquidHydrogen: _FieldDesc = _mk_field_ro()


class _ImportCount:
    ImportCount: _FieldDesc = _mk_field_ro()


class _ExportCount:
    ExportCount: _FieldDesc = _mk_field_ro()


class _Volume:
    Volume: _FieldDesc = _mk_field_ro()
    VolumeOfLiquid: _FieldDesc = _mk_field_ro()


class _Vertical:
    Horizontal: _FieldDesc = _mk_field_ro()
    Vertical: _FieldDesc = _mk_field_ro()


class _VerticalW:
    Horizontal: _FieldDescW = _mk_field()
    Vertical: _FieldDescW = _mk_field()


class _RecipeHash:
    RecipeHash: _FieldDescW = _mk_field()


class _Charge:
    Charge: _FieldDesc = _mk_field_ro()


class _Reagents:
    Reagents: _FieldDesc = _mk_field_ro()


class _Quantity:
    Quantity: _FieldDesc = _mk_field_ro()


class AccessBridge(_DeviceTyped, _Activate, _Lock, _Open, _Power):
    _hash: int = 1298920475


class LiquidDrain(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 1687692899


class ActiveVent(_DeviceTyped, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio, _SettingW):
    _hash: int = -1129453144
    PressureExternal: _FieldDescW = _mk_field()
    PressureInternal: _FieldDescW = _mk_field()


class AdvancedComposter(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _Power,
    _Quantity,
    _Ratio,
    _SettingW,
):
    _hash: int = 446212963


class AdvancedFurnace(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _ClearMemory,
    _Combustion,
    _Error,
    _ExportCount,
    _Hydrogen,
    _ImportCount,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _Reagents,
    _SettingW,
    _Temperature,
):
    _hash: int = 545937711
    RecipeHash: _FieldDesc = _mk_field_ro()
    SettingInput: _FieldDescW = _mk_field()
    SettingOutput: _FieldDescW = _mk_field()


class AdvancedPackagingMachine(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = -463037670
    CompletionRatio: _FieldDesc = _mk_field_ro()


class AirConditioner(
    _DeviceTyped,
    _BaseGasInput,
    _BaseGasOutput,
    _BaseGasOutput2,
    _Error,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = -2087593337
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    CombustionOutput2: _FieldDesc = _mk_field_ro()
    OperationalTemperatureEfficiency: _FieldDesc = _mk_field_ro()
    PressureEfficiency: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    PressureOutput2: _FieldDesc = _mk_field_ro()
    TemperatureDifferentialEfficiency: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TemperatureOutput2: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput2: _FieldDesc = _mk_field_ro()


class Airlock(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -2105052344


class ArcFurnace(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _Idle,
    _ImportCount,
    _Lock,
    _Power,
    _Reagents,
):
    _hash: int = -247344692
    RecipeHash: _FieldDesc = _mk_field_ro()


class AreaPowerControl(
    _DeviceTyped, _Charge, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio
):
    _hash: int = 1999523701
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class AreaPowerControlReversed(
    _DeviceTyped, _Charge, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio
):
    _hash: int = -1032513487
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class Autolathe(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = 336213101
    CompletionRatio: _FieldDesc = _mk_field_ro()


class AutomatedOven(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = -1672404896
    CompletionRatio: _FieldDesc = _mk_field_ro()


class AutoMinerSmall(
    _DeviceTyped, _Activate, _ClearMemory, _Error, _ExportCount, _ImportCount, _Open, _Power
):
    _hash: int = 7274344


class BatterySmall(_DeviceTyped, _Charge, _Maximum, _ModeR, _On, _Ratio):
    _hash: int = -2123455080
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class BackPressureRegulator(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -1149857558


class BasketHoop(_DeviceTyped, _Lock, _Power, _SettingW):
    _hash: int = -1613497288


class LogicBatchReader(_DeviceTyped, _Error, _Power, _SettingR):
    _hash: int = 264413729


class LogicBatchSlotReader(_DeviceTyped, _Error, _Power, _SettingR):
    _hash: int = 436888930


class LogicBatchWriter(_DeviceTyped, _Error, _Power):
    _hash: int = 1415443359
    ForceWrite: _FieldDescW = _mk_field()


class BatteryMedium(_DeviceTyped, _Charge, _Maximum, _ModeR, _On, _Ratio):
    _hash: int = -1125305264
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class BatteryCharger(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = 1945930022


class BatteryChargerSmall(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = -761772413


class Beacon(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = -188177083
    Color: _FieldDescW[_Color] = _mk_field(_Color)


class Bench1(_DeviceTyped, _Error, _Power):
    _hash: int = 406745009


class Bench3(_DeviceTyped, _Error, _Power):
    _hash: int = -164622691


class Bench2(_DeviceTyped, _Error, _Power):
    _hash: int = -2127086069


class Bench4(_DeviceTyped, _Error, _Power):
    _hash: int = 1750375230


class BlastDoor(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = 337416191


class BlockBed(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = 697908419


class LogicButton(_DeviceTyped, _Activate, _Lock, _SettingR):
    _hash: int = 491845673


class CableAnalysizer(_DeviceTyped):
    _hash: int = 1036015121
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()
    PowerRequired: _FieldDesc = _mk_field_ro()


class Camera(_DeviceTyped, _Mode, _On):
    _hash: int = -342072665


class CarbonSequester(
    _DeviceTyped,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Maximum,
    _Open,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = -865415211


class CargoStorageMedium(
    _DeviceTyped,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Quantity,
    _Ratio,
):
    _hash: int = 1151864003


class CargoStorageSmall(
    _DeviceTyped,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Quantity,
    _Ratio,
):
    _hash: int = -1493672123


class Centrifuge(
    _DeviceTyped, _ClearMemory, _Error, _ExportCount, _ImportCount, _Open, _Power, _Reagents
):
    _hash: int = 690945935


class ChuteDigitalFlipFlopSplitterLeft(_DeviceTyped, _Mode, _Power, _SettingW):
    _hash: int = -810874728
    Quantity: _FieldDescW = _mk_field()
    SettingOutput: _FieldDescW = _mk_field()


class ChuteDigitalFlipFlopSplitterRight(_DeviceTyped, _Mode, _Power, _SettingW):
    _hash: int = 163728359
    Quantity: _FieldDescW = _mk_field()
    SettingOutput: _FieldDescW = _mk_field()


class ChuteDigitalValveLeft(_DeviceTyped, _Lock, _Open, _Power, _SettingW):
    _hash: int = 648608238
    Quantity: _FieldDescW = _mk_field()


class ChuteDigitalValveRight(_DeviceTyped, _Lock, _Open, _Power, _SettingW):
    _hash: int = -1337091041
    Quantity: _FieldDescW = _mk_field()


class ChuteExportBin(_DeviceTyped, _Error, _Lock, _Open, _Power):
    _hash: int = 1957571043


class ChuteBin(_DeviceTyped, _Error, _Lock, _Open, _Power):
    _hash: int = -850484480


class ChuteInlet(_DeviceTyped, _ClearMemory, _ImportCount, _Lock):
    _hash: int = -1469588766


class ChuteOutlet(_DeviceTyped, _ClearMemory, _ExportCount, _ImportCount, _Lock):
    _hash: int = -1022714809


class CombustionCentrifuge(
    _DeviceTyped,
    _BaseGas,
    _BaseGasInput,
    _BaseGasOutput,
    _ClearMemory,
    _Combustion,
    _Error,
    _ExportCount,
    _Hydrogen,
    _ImportCount,
    _Lock,
    _Open,
    _PollWater,
    _Power,
    _Reagents,
    _Temperature,
):
    _hash: int = 1238905683
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionLimiter: _FieldDescW = _mk_field()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    Rpm: _FieldDesc = _mk_field_ro()
    Stress: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    Throttle: _FieldDescW = _mk_field()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()


class CompositeDoor(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -793837322


class CompositeWindowShutterController(_DeviceTyped, _Error, _Lock, _Open, _Power):
    _hash: int = -2078371660


class Computer(_DeviceTyped, _Error, _Lock, _Open, _Power):
    _hash: int = -626563514


class ComputerUpright(_DeviceTyped, _Error, _Lock, _Open, _Power):
    _hash: int = -405593895


class CondensationChamber(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _Maximum,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 1420719315


class CondensationValve(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = -965741795


class Console(_DeviceTyped, _Error, _Open, _Power, _SettingR):
    _hash: int = 235638270


class ConsoleDual(_DeviceTyped, _Error, _Open, _Power, _SettingR):
    _hash: int = -722284333


class ConsoleMonitor(_DeviceTyped, _Error, _Open, _Power, _SettingR):
    _hash: int = 801677497


class ControlChair(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _Mode,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -1961153710


class CornerLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = -1968255729


class PassthroughHeatExchangerGasToGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1674187440


class PassthroughHeatExchangerGasToLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1928991265


class PassthroughHeatExchangerLiquidToLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1472829583


class CryoTubeHorizontal(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Open, _Power, _Ratio, _SettingW, _Temperature
):
    _hash: int = 1443059329
    EntityState: _FieldDesc = _mk_field_ro()


class CryoTubeVertical(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Open, _Power, _Ratio, _SettingW, _Temperature
):
    _hash: int = -1381321828
    EntityState: _FieldDesc = _mk_field_ro()


class CryoTube(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Open, _Power, _Ratio, _SettingW, _Temperature
):
    _hash: int = 1938254586
    EntityState: _FieldDesc = _mk_field_ro()


class DaylightSensor(_DeviceTyped, _Activate, _Mode, _On, _Vertical):
    _hash: int = 1076425094
    SolarAngle: _FieldDesc = _mk_field_ro()
    SolarIrradiance: _FieldDesc = _mk_field_ro()


class DeepMiner(
    _DeviceTyped,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Maximum,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = 265720906


class LogicDial(_DeviceTyped, _Mode, _Ratio, _SettingW):
    _hash: int = 554524804


class DigitalValve(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -1280984102


class DiodeSlide(_DeviceTyped, _Lock, _Power, _SettingW):
    _hash: int = 576516101


class DispersalTower(
    _DeviceTyped,
    _BaseGasInput,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Maximum,
    _Open,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = -1868831137
    CombustionInput: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()


class DockPortSide(_DeviceTyped, _Idle, _Lock, _Open, _Power, _SettingW):
    _hash: int = -137465079


class DrinkingFountain(_DeviceTyped, _Error, _Power):
    _hash: int = 1968371847


class SleeperVerticalDroid(_DeviceTyped, _Activate, _Error, _Lock, _Open, _Power):
    _hash: int = 1382098999


class Electrolyzer(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _BaseGasInput,
    _BaseGasOutput,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -1668992663
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()


class ElectronicsPrinter(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = 1307165496
    CompletionRatio: _FieldDesc = _mk_field_ro()


class ElevatorLevelIndustrial(_DeviceTyped, _Activate, _Error, _Lock, _Open, _Power):
    _hash: int = 2060648791
    ElevatorLevel: _FieldDescW = _mk_field()
    ElevatorSpeed: _FieldDescW = _mk_field()


class ElevatorLevelFront(_DeviceTyped, _Activate, _Error, _Lock, _Open, _Power):
    _hash: int = -827912235
    ElevatorLevel: _FieldDescW = _mk_field()
    ElevatorSpeed: _FieldDescW = _mk_field()


class ElevatorShaftIndustrial(_DeviceTyped):
    _hash: int = 1998354978
    ElevatorLevel: _FieldDescW = _mk_field()
    ElevatorSpeed: _FieldDescW = _mk_field()


class ElevatorShaft(_DeviceTyped, _Power):
    _hash: int = 826144419
    ElevatorLevel: _FieldDescW = _mk_field()
    ElevatorSpeed: _FieldDescW = _mk_field()


class EvaporationChamber(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _Maximum,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -1429782576


class ExpansionValve(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = 195298587


class Filtration(
    _DeviceTyped,
    _BaseGasInput,
    _BaseGasOutput,
    _BaseGasOutput2,
    _Error,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = -348054045
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    CombustionOutput2: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    PressureOutput2: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TemperatureOutput2: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput2: _FieldDesc = _mk_field_ro()


class FlashingLight(_DeviceTyped, _Lock, _Power):
    _hash: int = -1535893860


class FridgeBig(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 958476921


class FridgeSmall(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 751887598


class Furnace(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _ClearMemory,
    _Combustion,
    _ExportCount,
    _Hydrogen,
    _ImportCount,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _PollWater,
    _Ratio,
    _Reagents,
    _SettingW,
    _Temperature,
):
    _hash: int = 1947944864
    RecipeHash: _FieldDesc = _mk_field_ro()


class MediumRocketGasFuelTank(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = -1093860567


class CapsuleTankGas(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = -1385712131


class GasGenerator(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 1165997963
    PowerGeneration: _FieldDesc = _mk_field_ro()


class GasMixer(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 2104106366


class GasSensor(_DeviceTyped, _BaseGas, _Hydrogen, _PollWater, _Temperature):
    _hash: int = -1252983604
    Combustion: _FieldDesc = _mk_field_ro()


class GasTankStorage(_DeviceTyped, _Quantity, _Temperature):
    _hash: int = 1632165346
    RatioCarbonDioxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogen: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygen: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutant: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatiles: _FieldDesc[float] = _mk_field_ro(float)
    RatioWater: _FieldDesc[float] = _mk_field_ro(float)


class SolidFuelGenerator(_DeviceTyped, _ClearMemory, _ImportCount, _Lock, _On):
    _hash: int = 813146305
    PowerGeneration: _FieldDesc = _mk_field_ro()


class GlassDoor(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -324331872


class GrowLight(_DeviceTyped, _Lock, _Power):
    _hash: int = -1758710260


class Harvie(
    _DeviceTyped, _Activate, _ClearMemory, _Error, _ExportCount, _ImportCount, _Lock, _Mode, _Power
):
    _hash: int = 958056199
    Harvest: _FieldDescW = _mk_field()
    Plant: _FieldDescW = _mk_field()


class HeatExchangeLiquidtoGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 944685608


class HeatExchangerGastoGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 21266291


class HeatExchangerLiquidtoLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -613784254


class HydraulicPipeBender(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = -1888248335
    CompletionRatio: _FieldDesc = _mk_field_ro()


class HydroponicsTrayData(_DeviceTyped, _BaseGas, _Combustion, _Hydrogen, _PollWater, _Temperature):
    _hash: int = -1841632400


class HydroponicsStation(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 1441767298


class CircuitHousing(_DeviceTyped, _Error, _Power, _SettingW):
    _hash: int = -128473777
    LineNumber: _FieldDescW = _mk_field()


class IceCrusher(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ImportCount,
    _Lock,
    _Maximum,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = 443849486


class Igniter(_DeviceTyped, _On):
    _hash: int = 1005491513


class EmergencyButton(_DeviceTyped, _Activate, _Error, _Lock, _Open, _Power, _SettingR):
    _hash: int = 1668452680


class IndustrialBurner(
    _DeviceTyped,
    _BaseGas,
    _ClearMemory,
    _Combustion,
    _Error,
    _ExportCount,
    _Hydrogen,
    _ImportCount,
    _Lock,
    _Maximum,
    _PollWater,
    _Power,
    _Ratio,
    _Reagents,
    _SettingW,
    _Temperature,
):
    _hash: int = 1493870235
    Activate: _FieldDescW = _mk_field()
    RecipeHash: _FieldDesc = _mk_field_ro()


class IndustrialCombustor(
    _DeviceTyped,
    _BaseGas,
    _BaseGasInput,
    _BaseGasOutput,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -586072380
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionInput2: _FieldDesc = _mk_field_ro()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureInput2: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    RatioCarbonDioxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidCarbonDioxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidNitrogenInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidNitrousOxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidOxygenInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidPollutantInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidVolatilesInput2: _FieldDesc = _mk_field_ro()
    RatioNitrogenInput2: _FieldDesc = _mk_field_ro()
    RatioNitrousOxideInput2: _FieldDesc = _mk_field_ro()
    RatioOxygenInput2: _FieldDesc = _mk_field_ro()
    RatioPollutantInput2: _FieldDesc = _mk_field_ro()
    RatioSteamInput2: _FieldDesc = _mk_field_ro()
    RatioVolatilesInput2: _FieldDesc = _mk_field_ro()
    RatioWaterInput2: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureInput2: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesInput2: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()


class IndustrialFiltration(
    _DeviceTyped,
    _BaseGasOutput,
    _BaseGasOutput2,
    _Error,
    _Lock,
    _Maximum,
    _Mode,
    _Open,
    _Power,
    _Ratio,
    _SettingW,
):
    _hash: int = 1167018773
    CombustionOutput: _FieldDesc = _mk_field_ro()
    CombustionOutput2: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    PressureOutput2: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TemperatureOutput2: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()
    TotalMolesOutput2: _FieldDesc = _mk_field_ro()


class InteriorDoorGlass(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -2096421875


class InteriorDoorPadded(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = 847461335


class InteriorDoorPaddedThin(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = 1981698201


class InteriorDoorTriangle(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -1182923101


class Klaxon(_DeviceTyped, _Mode, _Power):
    _hash: int = -828056979
    SoundAlert: _FieldDescW = _mk_field()
    Volume: _FieldDescW = _mk_field()


class RoboticArmDock(_DeviceTyped, _Activate, _Error, _Idle, _Power, _SettingW):
    _hash: int = -1818718810
    Extended: _FieldDesc = _mk_field_ro()
    PositionX: _FieldDesc = _mk_field_ro()


class LarreDockAtmos(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _BaseGasInput,
    _Combustion,
    _Error,
    _Hydrogen,
    _Idle,
    _Mode,
    _Open,
    _PollWater,
    _Power,
    _SettingW,
    _Temperature,
):
    _hash: int = 1978422481
    CombustionInput: _FieldDesc = _mk_field_ro()
    Extended: _FieldDesc = _mk_field_ro()
    PositionX: _FieldDesc = _mk_field_ro()
    PressureExternal: _FieldDescW = _mk_field()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureInternal: _FieldDescW = _mk_field()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()


class LarreDockBypass(_DeviceTyped, _Open, _Power):
    _hash: int = 1011275082


class LarreDockCargo(_DeviceTyped, _Activate, _Error, _Idle, _Open, _Power, _SettingW):
    _hash: int = -1555459562
    Extended: _FieldDesc = _mk_field_ro()
    PositionX: _FieldDesc = _mk_field_ro()
    TargetPrefabHash: _FieldDesc = _mk_field_ro()
    TargetSlotIndex: _FieldDescW = _mk_field()


class LarreDockCollector(
    _DeviceTyped, _Activate, _Error, _Idle, _Mode, _Open, _Power, _Quantity, _Ratio, _SettingW
):
    _hash: int = -522428667
    Extended: _FieldDesc = _mk_field_ro()
    PositionX: _FieldDesc = _mk_field_ro()


class LarreDockHydroponics(_DeviceTyped, _Activate, _Error, _Idle, _Open, _Power, _SettingW):
    _hash: int = 85133079
    Extended: _FieldDesc = _mk_field_ro()
    PositionX: _FieldDesc = _mk_field_ro()
    TargetPrefabHash: _FieldDesc = _mk_field_ro()
    TargetSlotIndex: _FieldDesc = _mk_field_ro()


class Diode(_DeviceTyped, _Lock, _Power):
    _hash: int = 1944485013
    Color: _FieldDescW[_Color] = _mk_field(_Color)


class ConsoleLED1x3(_DeviceTyped, _Error, _Mode, _Power, _SettingW):
    _hash: int = -1949054743
    Color: _FieldDescW[_Color] = _mk_field(_Color)


class ConsoleLED1x2(_DeviceTyped, _Error, _Mode, _Power, _SettingW):
    _hash: int = -53151617
    Color: _FieldDescW[_Color] = _mk_field(_Color)


class ConsoleLED5(_DeviceTyped, _Error, _Mode, _Power, _SettingW):
    _hash: int = -815193061
    Color: _FieldDescW[_Color] = _mk_field(_Color)


class LargeDirectHeatExchangeLiquidtoLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 792686502


class LargeDirectHeatExchangeGastoGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1230658883


class LargeDirectHeatExchangeGastoLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1412338038


class LargeExtendableRadiator(_DeviceTyped, _Lock, _Maximum, _Open, _Ratio, _SettingW):
    _hash: int = -566775170
    Horizontal: _FieldDescW = _mk_field()


class LargeHangerDoor(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -1351081801


class LargeSatelliteDish(_DeviceTyped, _Activate, _Error, _Idle, _Power, _SettingW, _VerticalW):
    _hash: int = 1913391845
    BestContactFilter: _FieldDescW = _mk_field()
    ContactTypeId: _FieldDesc = _mk_field_ro()
    InterrogationProgress: _FieldDesc = _mk_field_ro()
    MinimumWattsToContact: _FieldDesc = _mk_field_ro()
    SignalID: _FieldDesc = _mk_field_ro()
    SignalStrength: _FieldDesc = _mk_field_ro()
    SizeX: _FieldDesc = _mk_field_ro()
    SizeZ: _FieldDesc = _mk_field_ro()
    TargetPadIndex: _FieldDescW = _mk_field()
    WattsReachingContact: _FieldDesc = _mk_field_ro()


class TankBig(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = -1606848156


class LogicSwitch(_DeviceTyped, _Lock, _Open, _SettingR):
    _hash: int = 1220484876


class LightRound(_DeviceTyped, _Lock, _Power):
    _hash: int = 1514476632


class LightRoundAngled(_DeviceTyped, _Lock, _Power):
    _hash: int = 1592905386


class LightRoundSmall(_DeviceTyped, _Lock, _Power):
    _hash: int = 1436121888


class RobotArmDoor(_DeviceTyped, _Open):
    _hash: int = -2131782367
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    RequiredPower: _FieldDesc[int] = _mk_field_ro(int)


class BackLiquidPressureRegulator(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 2099900163


class MediumRocketLiquidFuelTank(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1143639539


class CapsuleTankLiquid(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1415396263


class WaterDigitalValve(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -517628750


class LiquidPipeAnalyzer(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _PollWater,
    _Power,
    _Temperature,
    _Volume,
):
    _hash: int = -2113838091


class LiquidTankBig(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1098900430


class LiquidTankBigInsulated(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = -1430440215


class LiquidTankSmall(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1988118157


class LiquidTankSmallInsulated(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 608607718


class LiquidTankStorage(_DeviceTyped, _Quantity, _Temperature):
    _hash: int = 1691898022
    RatioCarbonDioxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrogen: _FieldDesc[float] = _mk_field_ro(float)
    RatioNitrousOxide: _FieldDesc[float] = _mk_field_ro(float)
    RatioOxygen: _FieldDesc[float] = _mk_field_ro(float)
    RatioPollutant: _FieldDesc[float] = _mk_field_ro(float)
    RatioVolatiles: _FieldDesc[float] = _mk_field_ro(float)
    RatioWater: _FieldDesc[float] = _mk_field_ro(float)


class LiquidVolumePump(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -454028979


class LiquidPressureRegulator(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 482248766


class WaterWallCooler(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -1369060582


class StorageLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = -793623899


class LockerSmall(_DeviceTyped, _Lock, _Open):
    _hash: int = -647164662


class LogicCompare(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = -1489728908


class LogicGate(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = 1942143074


class LogicHashGen(_DeviceTyped, _SettingR):
    _hash: int = 2077593121


class LogicMath(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = 1657691323


class LogicMemory(_DeviceTyped, _SettingW):
    _hash: int = -851746783


class LogicMinMax(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = 929022276


class LogicReader(_DeviceTyped, _Error, _Power, _SettingR):
    _hash: int = -345383640


class LogicRocketDownlink(_DeviceTyped):
    _hash: int = 876108549
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    RequiredPower: _FieldDesc[int] = _mk_field_ro(int)


class LogicSelect(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = 1822736084


class LogicSorter(
    _DeviceTyped, _ClearMemory, _Error, _ExportCount, _ImportCount, _Lock, _Mode, _Power
):
    _hash: int = 873418029


class LogicRocketUplink(_DeviceTyped, _Error, _Power):
    _hash: int = 546002924


class LogicWriter(_DeviceTyped, _Error, _Power):
    _hash: int = -1326019434
    ForceWrite: _FieldDescW = _mk_field()


class LogicWriterSwitch(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = -1321250424
    ForceWrite: _FieldDescW = _mk_field()


class ManualFloorHatch(_DeviceTyped, _Idle, _Lock, _Open, _SettingW):
    _hash: int = 1435578852


class ManualHatch(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -1808154199


class LogicMathUnary(_DeviceTyped, _Error, _Mode, _Power, _SettingR):
    _hash: int = -1160020195


class MediumConvectionRadiator(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1918215845


class PassiveLargeRadiatorGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 2066977095


class MediumConvectionRadiatorLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1169014183


class PassiveLargeRadiatorLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 24786172


class MediumHangerDoor(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = -566348148


class MediumRadiator(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -975966237


class MediumRadiatorLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1141760613


class SatelliteDish(_DeviceTyped, _Activate, _Error, _Idle, _Power, _SettingW, _VerticalW):
    _hash: int = 439026183
    BestContactFilter: _FieldDescW = _mk_field()
    ContactTypeId: _FieldDesc = _mk_field_ro()
    InterrogationProgress: _FieldDesc = _mk_field_ro()
    MinimumWattsToContact: _FieldDesc = _mk_field_ro()
    SignalID: _FieldDesc = _mk_field_ro()
    SignalStrength: _FieldDesc = _mk_field_ro()
    SizeX: _FieldDesc = _mk_field_ro()
    SizeZ: _FieldDesc = _mk_field_ro()
    TargetPadIndex: _FieldDescW = _mk_field()
    WattsReachingContact: _FieldDesc = _mk_field_ro()


class PowerTransmitterReceiver(_DeviceTyped, _Charge, _Error, _ModeR, _Power, _VerticalW):
    _hash: int = 1195820278
    PositionX: _FieldDesc = _mk_field_ro()
    PositionY: _FieldDesc = _mk_field_ro()
    PositionZ: _FieldDesc = _mk_field_ro()
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class PowerTransmitter(_DeviceTyped, _Charge, _Error, _ModeR, _Power, _VerticalW):
    _hash: int = -65087121
    PositionX: _FieldDesc = _mk_field_ro()
    PositionY: _FieldDesc = _mk_field_ro()
    PositionZ: _FieldDesc = _mk_field_ro()
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class MotionSensor(_DeviceTyped, _Activate, _On, _Quantity):
    _hash: int = -1713470563


class Nitrolyzer(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _BaseGasInput,
    _BaseGasOutput,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _Mode,
    _Open,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 1898243702
    CombustionInput: _FieldDesc = _mk_field_ro()
    CombustionInput2: _FieldDesc = _mk_field_ro()
    CombustionOutput: _FieldDesc = _mk_field_ro()
    PressureInput: _FieldDesc = _mk_field_ro()
    PressureInput2: _FieldDesc = _mk_field_ro()
    PressureOutput: _FieldDesc = _mk_field_ro()
    RatioCarbonDioxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidCarbonDioxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidNitrogenInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidNitrousOxideInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidOxygenInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidPollutantInput2: _FieldDesc = _mk_field_ro()
    RatioLiquidVolatilesInput2: _FieldDesc = _mk_field_ro()
    RatioNitrogenInput2: _FieldDesc = _mk_field_ro()
    RatioNitrousOxideInput2: _FieldDesc = _mk_field_ro()
    RatioOxygenInput2: _FieldDesc = _mk_field_ro()
    RatioPollutantInput2: _FieldDesc = _mk_field_ro()
    RatioSteamInput2: _FieldDesc = _mk_field_ro()
    RatioVolatilesInput2: _FieldDesc = _mk_field_ro()
    RatioWaterInput2: _FieldDesc = _mk_field_ro()
    TemperatureInput: _FieldDesc = _mk_field_ro()
    TemperatureInput2: _FieldDesc = _mk_field_ro()
    TemperatureOutput: _FieldDesc = _mk_field_ro()
    TotalMolesInput: _FieldDesc = _mk_field_ro()
    TotalMolesInput2: _FieldDesc = _mk_field_ro()
    TotalMolesOutput: _FieldDesc = _mk_field_ro()


class HorizontalAutoMiner(
    _DeviceTyped, _Activate, _ClearMemory, _Error, _ExportCount, _ImportCount, _Mode, _Open, _Power
):
    _hash: int = 1070427573


class OccupancySensor(_DeviceTyped, _Quantity):
    _hash: int = 322782515
    Activate: _FieldDesc = _mk_field_ro()


class PipeOneWayValveLever(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = 1289581593


class PipeLiquidOneWayValveLever(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = -523832822


class OverheadShortCornerLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = -1794932560


class OverheadShortLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = 1468249454


class PipeAnalysizer(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Lock,
    _PollWater,
    _Power,
    _Temperature,
    _Volume,
):
    _hash: int = 435685051


class PipeHeater(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = -419758574


class LiquidPipeHeater(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = -287495560


class PipeIgniter(_DeviceTyped, _Activate, _Error):
    _hash: int = 1286441942
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    RequiredPower: _FieldDesc[int] = _mk_field_ro(int)


class PortablesConnector(_DeviceTyped, _Maximum, _Open, _Ratio, _SettingW):
    _hash: int = -899013427


class PowerConnector(_DeviceTyped, _Open):
    _hash: int = -782951720


class PowerTransmitterOmni(_DeviceTyped, _Error, _Power):
    _hash: int = -327468845


class Bench(_DeviceTyped, _Error, _Power):
    _hash: int = -2042448192


class PoweredVent(_DeviceTyped, _Error, _Lock, _Mode, _Power):
    _hash: int = 938836756
    PressureExternal: _FieldDescW = _mk_field()


class PoweredVentLarge(_DeviceTyped, _Error, _Lock, _Mode, _Power):
    _hash: int = -785498334
    PressureExternal: _FieldDescW = _mk_field()


class PressurantValve(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 23052817


class PressureFedGasEngine(
    _DeviceTyped, _BaseGas, _Combustion, _Error, _Hydrogen, _PollWater, _Power, _Temperature
):
    _hash: int = -624011170
    PassedMoles: _FieldDesc = _mk_field_ro()
    Throttle: _FieldDescW = _mk_field()


class PressureFedLiquidEngine(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = 379750958
    PassedMoles: _FieldDesc = _mk_field_ro()
    Throttle: _FieldDescW = _mk_field()


class PressureRegulator(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 209854039


class ProximitySensor(_DeviceTyped, _Quantity, _SettingW):
    _hash: int = 568800213
    Activate: _FieldDesc = _mk_field_ro()


class GovernedGasEngine(
    _DeviceTyped, _BaseGas, _Combustion, _Error, _Hydrogen, _PollWater, _Power, _Temperature
):
    _hash: int = -214232602
    PassedMoles: _FieldDesc = _mk_field_ro()
    Throttle: _FieldDescW = _mk_field()


class PumpedLiquidEngine(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Power,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -2031440019
    PassedMoles: _FieldDesc = _mk_field_ro()
    Throttle: _FieldDescW = _mk_field()


class PurgeValve(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -737232128


class LogicReagentReader(_DeviceTyped, _Error, _Power, _SettingR):
    _hash: int = -124308857


class Recycler(
    _DeviceTyped, _Activate, _ClearMemory, _Error, _ExportCount, _ImportCount, _Power, _Reagents
):
    _hash: int = -1633947337


class RefrigeratedVendingMachine(
    _DeviceTyped,
    _Activate,
    _BaseGas,
    _ClearMemory,
    _Combustion,
    _Error,
    _ExportCount,
    _Hydrogen,
    _ImportCount,
    _Lock,
    _PollWater,
    _Power,
    _Quantity,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -1577831321
    RequestHash: _FieldDescW = _mk_field()


class RocketAvionics(
    _DeviceTyped, _BaseGas, _Error, _Hydrogen, _Mode, _PollWater, _Power, _Quantity, _Reagents
):
    _hash: int = 808389066
    Acceleration: _FieldDesc = _mk_field_ro()
    Altitude: _FieldDesc = _mk_field_ro()
    Apex: _FieldDesc = _mk_field_ro()
    AutoLand: _FieldDescW = _mk_field()
    AutoShutOff: _FieldDescW = _mk_field()
    BurnTimeRemaining: _FieldDesc = _mk_field_ro()
    Chart: _FieldDesc = _mk_field_ro()
    ChartedNavPoints: _FieldDesc = _mk_field_ro()
    CurrentCode: _FieldDesc = _mk_field_ro()
    Density: _FieldDesc = _mk_field_ro()
    DestinationCode: _FieldDescW = _mk_field()
    Discover: _FieldDesc = _mk_field_ro()
    DryMass: _FieldDesc = _mk_field_ro()
    FlightControlRule: _FieldDesc = _mk_field_ro()
    Mass: _FieldDesc = _mk_field_ro()
    MinedQuantity: _FieldDesc = _mk_field_ro()
    NavPoints: _FieldDesc = _mk_field_ro()
    Progress: _FieldDesc = _mk_field_ro()
    ReEntryAltitude: _FieldDesc = _mk_field_ro()
    Richness: _FieldDesc = _mk_field_ro()
    Sites: _FieldDesc = _mk_field_ro()
    Size: _FieldDesc = _mk_field_ro()
    Survey: _FieldDesc = _mk_field_ro()
    Temperature: _FieldDesc = _mk_field_ro()
    Thrust: _FieldDesc = _mk_field_ro()
    ThrustToWeight: _FieldDesc = _mk_field_ro()
    TimeToDestination: _FieldDesc = _mk_field_ro()
    TotalMoles: _FieldDesc = _mk_field_ro()
    TotalQuantity: _FieldDesc = _mk_field_ro()
    VelocityRelativeY: _FieldDesc = _mk_field_ro()
    Weight: _FieldDesc = _mk_field_ro()


class RocketCargoBay(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = -682274666


class RocketCelestialTracker(_DeviceTyped, _Error, _Power, _Vertical):
    _hash: int = 997453927
    CelestialHash: _FieldDesc = _mk_field_ro()
    Index: _FieldDescW = _mk_field()


class RocketCircuitHousing(_DeviceTyped, _Error, _Power, _SettingW):
    _hash: int = 150135861
    LineNumber: _FieldDescW = _mk_field()


class RocketEngineTiny(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 178472613


class RocketManufactory(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = 1781051034
    CompletionRatio: _FieldDesc = _mk_field_ro()


class RocketMiner(
    _DeviceTyped, _ClearMemory, _Error, _ExportCount, _ImportCount, _Lock, _Power, _Quantity
):
    _hash: int = -2087223687
    DrillCondition: _FieldDesc = _mk_field_ro()


class RocketScanner(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = 2014252591


class SDBHopper(_DeviceTyped, _ClearMemory, _ImportCount, _Open):
    _hash: int = -1875856925


class SDBHopperAdvanced(_DeviceTyped, _ClearMemory, _ImportCount, _Lock, _Open):
    _hash: int = 467225612


class SDBSilo(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Mode,
    _Open,
    _Power,
    _Quantity,
):
    _hash: int = 1155865682


class SecurityPrinter(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = -641491515
    CompletionRatio: _FieldDesc = _mk_field_ro()


class ShelfMedium(_DeviceTyped, _Open):
    _hash: int = 182006674


class ShortCornerLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = 1330754486


class ShortLocker(_DeviceTyped, _Lock, _Open):
    _hash: int = -554553467


class Shower(_DeviceTyped, _Activate, _Maximum, _Open, _Ratio, _SettingW):
    _hash: int = -775128944


class ShowerPowered(_DeviceTyped, _Error, _Open, _Power):
    _hash: int = -1081797501


class Sleeper(_DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Open, _Power, _Ratio, _SettingW):
    _hash: int = -1467449329
    EntityState: _FieldDesc = _mk_field_ro()


class SleeperLeft(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio, _SettingW
):
    _hash: int = 1213495833
    EntityState: _FieldDesc = _mk_field_ro()


class SleeperRight(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio, _SettingW
):
    _hash: int = -1812330717
    EntityState: _FieldDesc = _mk_field_ro()


class SleeperVertical(
    _DeviceTyped, _Activate, _Error, _Lock, _Maximum, _Mode, _Open, _Power, _Ratio, _SettingW
):
    _hash: int = -1300059018
    EntityState: _FieldDesc = _mk_field_ro()


class LogicSlotReader(_DeviceTyped, _Error, _Power, _SettingR):
    _hash: int = -767867194


class SmallDirectHeatExchangeGastoGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1310303582


class SmallDirectHeatExchangeLiquidtoGas(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1825212016


class SmallDirectHeatExchangeLiquidtoLiquid(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -507770416


class AirlockGate(_DeviceTyped, _Idle, _Lock, _Mode, _Open, _Power, _SettingW):
    _hash: int = 1736080881


class SmallSatelliteDish(_DeviceTyped, _Activate, _Error, _Idle, _Power, _SettingW, _VerticalW):
    _hash: int = -2138748650
    BestContactFilter: _FieldDescW = _mk_field()
    ContactTypeId: _FieldDesc = _mk_field_ro()
    InterrogationProgress: _FieldDesc = _mk_field_ro()
    MinimumWattsToContact: _FieldDesc = _mk_field_ro()
    SignalID: _FieldDesc = _mk_field_ro()
    SignalStrength: _FieldDesc = _mk_field_ro()
    SizeX: _FieldDesc = _mk_field_ro()
    SizeZ: _FieldDesc = _mk_field_ro()
    TargetPadIndex: _FieldDescW = _mk_field()
    WattsReachingContact: _FieldDesc = _mk_field_ro()


class TankSmall(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1013514688


class TankSmallAir(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 955744474


class TankSmallFuel(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 2102454415


class SolarPanel(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = -2045627372


class SolarPanel45(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = -1554349863


class SolarPanelDual(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = -539224550


class SolarPanelFlat(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = 1968102968


class SolarPanel45Reinforced(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = 930865127


class SolarPanelDualReinforced(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = -1545574413


class SolarPanelFlatReinforced(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = 1697196770


class SolarPanelReinforced(_DeviceTyped, _Charge, _Maximum, _Ratio, _VerticalW):
    _hash: int = -934345724


class Sorter(_DeviceTyped, _ClearMemory, _Error, _ExportCount, _ImportCount, _Lock, _Mode, _Power):
    _hash: int = -1009150565
    Output: _FieldDescW = _mk_field()


class StackerReverse(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Mode,
    _Power,
    _SettingW,
):
    _hash: int = 1585641623
    Output: _FieldDescW = _mk_field()


class Stacker(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Mode,
    _Power,
    _SettingW,
):
    _hash: int = -2020231820
    Output: _FieldDescW = _mk_field()


class Battery(_DeviceTyped, _Charge, _Error, _Lock, _Maximum, _ModeR, _On, _Ratio):
    _hash: int = -400115994
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class BatteryLarge(_DeviceTyped, _Charge, _Error, _Lock, _Maximum, _ModeR, _On, _Ratio):
    _hash: int = -1388288459
    Power: _FieldDesc[bool] = _mk_field_ro(bool)
    PowerActual: _FieldDesc = _mk_field_ro()
    PowerPotential: _FieldDesc = _mk_field_ro()


class StirlingEngine(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Error,
    _Hydrogen,
    _Maximum,
    _PollWater,
    _Power,
    _Quantity,
    _Ratio,
    _SettingW,
    _Temperature,
):
    _hash: int = -260316435
    EnvironmentEfficiency: _FieldDesc = _mk_field_ro()
    PowerGeneration: _FieldDesc = _mk_field_ro()
    Volume: _FieldDesc = _mk_field_ro()
    WorkingGasEfficiency: _FieldDesc = _mk_field_ro()


class SuitStorage(_DeviceTyped, _Error, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 255034731


class LogicSwitch2(_DeviceTyped, _Lock, _Open, _SettingR):
    _hash: int = 321604921


class TankBigInsulated(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 1280378227


class TankSmallInsulated(
    _DeviceTyped,
    _BaseGas,
    _Combustion,
    _Hydrogen,
    _Maximum,
    _Open,
    _PollWater,
    _Ratio,
    _SettingW,
    _Temperature,
    _Volume,
):
    _hash: int = 272136332


class GroundBasedTelescope(_DeviceTyped, _Activate, _Error, _Lock, _Open, _Power, _VerticalW):
    _hash: int = -619745681
    AlignmentError: _FieldDesc = _mk_field_ro()
    CelestialHash: _FieldDesc = _mk_field_ro()
    CelestialParentHash: _FieldDesc = _mk_field_ro()
    DistanceAu: _FieldDesc = _mk_field_ro()
    DistanceKm: _FieldDesc = _mk_field_ro()
    Eccentricity: _FieldDesc = _mk_field_ro()
    HorizontalRatio: _FieldDescW = _mk_field()
    Inclination: _FieldDesc = _mk_field_ro()
    OrbitPeriod: _FieldDesc = _mk_field_ro()
    SemiMajorAxis: _FieldDesc = _mk_field_ro()
    TrueAnomaly: _FieldDesc = _mk_field_ro()
    VerticalRatio: _FieldDescW = _mk_field()


class TerraformingManufactory(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = 1549873866
    CompletionRatio: _FieldDesc = _mk_field_ro()


class ToolManufactory(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Open,
    _Power,
    _Reagents,
    _RecipeHash,
):
    _hash: int = -465741100
    CompletionRatio: _FieldDesc = _mk_field_ro()


class TraderWaypoint(_DeviceTyped, _Error, _Power):
    _hash: int = 1570931620


class Transformer(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -1423212473


class TransformerMedium(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -1065725831


class TransformerSmall(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -890946730


class TransformerMediumReversed(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 833912764


class TransformerSmallReversed(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 1054059374


class RocketTransformerSmall(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = 518925193


class PressurePlateLarge(_DeviceTyped, _SettingR):
    _hash: int = -2008706143


class PressurePlateMedium(_DeviceTyped, _SettingR):
    _hash: int = 1269458680


class PressurePlateSmall(_DeviceTyped, _SettingR):
    _hash: int = -1536471028


class TurbineGenerator(_DeviceTyped):
    _hash: int = 1282191063
    PowerGeneration: _FieldDesc = _mk_field_ro()


class TurboVolumePump(_DeviceTyped, _Error, _Lock, _Maximum, _Mode, _Power, _Ratio, _SettingW):
    _hash: int = 1310794736


class LiquidTurboVolumePump(
    _DeviceTyped, _Error, _Lock, _Maximum, _Mode, _Power, _Ratio, _SettingW
):
    _hash: int = -1051805505


class ChuteUmbilicalMale(_DeviceTyped, _Error, _Lock, _ModeR, _Open, _Power):
    _hash: int = -958884053


class GasUmbilicalMale(
    _DeviceTyped, _Error, _Lock, _Maximum, _ModeR, _Open, _Power, _Ratio, _SettingW
):
    _hash: int = -1814939203


class LiquidUmbilicalMale(
    _DeviceTyped, _Error, _Lock, _Maximum, _ModeR, _Open, _Power, _Ratio, _SettingW
):
    _hash: int = -1798420047


class PowerUmbilicalMale(_DeviceTyped, _Error, _Lock, _ModeR, _Open, _Power):
    _hash: int = 1529453938


class GasUmbilicalFemale(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -1680477930


class LiquidUmbilicalFemale(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1734723642


class GasUmbilicalFemaleSide(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = -648683847


class LiquidUmbilicalFemaleSide(_DeviceTyped, _Maximum, _Ratio, _SettingW):
    _hash: int = 1220870319


class Unloader(
    _DeviceTyped, _ClearMemory, _Error, _ExportCount, _ImportCount, _Lock, _Mode, _Power
):
    _hash: int = 750118160
    Output: _FieldDescW = _mk_field()


class UprightWindTurbine(_DeviceTyped):
    _hash: int = 1622183451
    PowerGeneration: _FieldDesc = _mk_field_ro()


class Valve(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = -692036078


class LiquidValve(_DeviceTyped, _Maximum, _On, _Ratio, _SettingW):
    _hash: int = 1849974453


class VendingMachine(
    _DeviceTyped,
    _Activate,
    _ClearMemory,
    _Error,
    _ExportCount,
    _ImportCount,
    _Lock,
    _Power,
    _Quantity,
    _Ratio,
):
    _hash: int = -443130773
    RequestHash: _FieldDescW = _mk_field()


class VolumePump(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -321403609


class WallCooler(_DeviceTyped, _Error, _Lock, _Maximum, _Power, _Ratio, _SettingW):
    _hash: int = -739292323


class WallHeater(_DeviceTyped, _Error, _Lock, _Power):
    _hash: int = 24258244


class WallLight(_DeviceTyped, _Lock, _Power):
    _hash: int = -1860064656


class WallLightBattery(_DeviceTyped, _Lock, _Power):
    _hash: int = -1306415132


class LightLongAngled(_DeviceTyped, _Lock, _Power):
    _hash: int = 1847265835


class LightLongWide(_DeviceTyped, _Lock, _Power):
    _hash: int = 555215790


class LightLong(_DeviceTyped, _Lock, _Power):
    _hash: int = 797794350


class WaterBottleFiller(_DeviceTyped, _Activate, _Error):
    _hash: int = -1178961954


class WaterBottleFillerBottom(_DeviceTyped, _Activate, _Error):
    _hash: int = 1433754995


class WaterPurifier(_DeviceTyped, _ClearMemory, _Error, _ImportCount, _Lock, _Power):
    _hash: int = 887383294


class WaterBottleFillerPoweredBottom(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = 1986658780


class WaterBottleFillerPowered(_DeviceTyped, _Activate, _Error, _Power):
    _hash: int = -756587791


class WeatherStation(_DeviceTyped, _Activate, _Error, _Lock, _ModeR, _Power):
    _hash: int = 1997212478
    NextWeatherEventTime: _FieldDesc = _mk_field_ro()


class WindTurbine(_DeviceTyped):
    _hash: int = -2082355173
    PowerGeneration: _FieldDesc = _mk_field_ro()
