name: CI

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.9"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: black
        run: uv run black --check .

      - name: isort
        run: uv run isort --check .

      - name: pyright
        run: uv run pyright .

      - name: basedpyright
        run: uv run basedpyright .

      - name: pytest
        run: uv run pytest -s --cov=sicc --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
